spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false


  mustache:
    suffix: .html
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306?serverTimezone=UTC
    username: user1
    password: test123
