spring:
  datasource:
    url: jdbc:mysql://hotthinkdatabase.cjditpwe7bq8.ap-northeast-2.rds.amazonaws.com/HotThink?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: admin
    password: test1234
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  mustache:
    suffix: .html
  profiles:
    include: oauth
  kafka:
    bootstrap-servers: 13.209.73.144:9092
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
