spring:
  datasource:
    url: jdbc:mysql://localhost:3306?serverTimezone=UTC
    username: user1
    password: test123
    driver-class-name: com.mysql.jdbc.Driver

  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  mustache:
    suffix: .html


