spring:
  datasource:
    url: jdbc:mysql://hotthinkdatabase.cjditpwe7bq8.ap-northeast-2.rds.amazonaws.com/HotThink?serverTimezone=UTC
    username: admin
    password: test1234
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  mustache:
    suffix: .html


